version: '3.1'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=cuidapet_db
      - MYSQL_ROOT_PASSWORD=cuidapet
    volumes:
      - ./mysql_data:/var/lib/mysql
